# Generated by Django 3.0.3 on 2020-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='PDF_Files')),
                ('lines', models.CharField(max_length=50)),
            ],
        ),
    ]
