# Generated by Django 3.0.3 on 2020-08-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0002_c_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C_Program',
            new_name='CProgram',
        ),
    ]
