# Generated by Django 3.0.3 on 2020-08-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0003_auto_20200820_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CProgram',
        ),
    ]
