# Generated by Django 3.0.3 on 2020-08-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0004_delete_cprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfs', models.FileField(upload_to='PDFS')),
                ('lines', models.CharField(max_length=50)),
            ],
        ),
    ]
