# Generated by Django 3.0.3 on 2020-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0005_cprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudComputing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_pdfs', models.FileField(upload_to='CCPDFS')),
                ('cc_lines', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_pdfs', models.FileField(upload_to='DSPDFS')),
                ('ds_lines', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EthicalHack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack_pdfs', models.FileField(upload_to='EHPDFS')),
                ('hack_lines', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JAVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_pdfs', models.FileField(upload_to='JPDFS')),
                ('j_lines', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_pdfs', models.FileField(upload_to='NetPDFS')),
                ('net_lines', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_pdfs', models.FileField(upload_to='OSPDFS')),
                ('os_lines', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('py_pdfs', models.FileField(upload_to='PYPDFS')),
                ('py_lines', models.CharField(max_length=50)),
            ],
        ),
    ]
